//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Discounts')
export class DiscountsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  product: number;

  @Column('text', { nullable: true })
  discountType: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('real', { nullable: true })
  discountAmount: number;

  @Column('real', { nullable: true })
  discountPercent: number;
}
