//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const OrdersTitle = () => {
  const record = useRecordContext();
  return <span>Orders {record ? `"${record.id}"` : ''}</span>;
};

export const OrdersList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="orderNumber" />
      <ReferenceField source="customer" reference="Customers" />
      <NumberField source="totalAmount" />
      <NumberField source="vat" />
      <NumberField source="totalAmountWithVat" />
      <NumberField source="shippingCost" />
      <TextField source="shippingAddress" />
      <TextField source="orderAddress" />
      <EmailField source="orderEmail" />
      <DateField source="orderDate" />
      <TextField source="orderStatus" />
      <TextField source="trackingNo" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const OrdersEdit = () => (
  <Edit title={<OrdersTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="orderNumber" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="customer" reference="Customers" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="totalAmount" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="vat" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="totalAmountWithVat" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="shippingCost" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="shippingAddress" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="orderAddress" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="orderEmail" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="orderDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="orderStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="trackingNo" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const OrdersCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="orderNumber" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="customer" reference="Customers" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="totalAmount" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="vat" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="totalAmountWithVat" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="shippingCost" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="shippingAddress" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="orderAddress" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="orderEmail" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="orderDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="orderStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="trackingNo" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="customer"
    label="customer"
    reference="Customers"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
